apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: minecraft
resources:
  - configmap.yaml
  - minecraft-rcon-secret-sealedsecret.yaml
  - helmrelease.yaml
  - networkpolicy.yaml
  - bluemap-service.yaml
  - pvc-minecraft-datadir.yaml
